abstract: The great new Cog!
author: "Ingy d\xC3\xB6t Net, C<< <ingy at cpan.org> >>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Cog
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.6.1
version: 0.01
